# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bgg 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "bgg"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jeremiah Lee", "Brett Hardin"]
  s.date = "2014-05-08"
  s.description = "Object-oriented interface for interacting with Boardgamegeek API"
  s.email = "jeremiah.lee@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bgg.gemspec",
    "lib/bgg.rb",
    "lib/bgg/collection.rb",
    "lib/bgg/collection_item.rb",
    "lib/bgg/game.rb",
    "lib/bgg/play.rb",
    "lib/bgg/plays.rb",
    "lib/bgg/plays_iterator.rb",
    "lib/bgg/search.rb",
    "lib/bgg/search_result.rb",
    "lib/bgg/user.rb",
    "sample_data/collection?username=texasjdl",
    "sample_data/collection?username=texasjdl&own=1&excludesubtype=boardgameexpansion",
    "sample_data/collection?username=yyyyyyy",
    "sample_data/hot?type=boardgame",
    "sample_data/plays?pages=9999999999999&username=ryanmacg",
    "sample_data/plays?username=beetss&page=1",
    "sample_data/plays?username=ryanmacg",
    "sample_data/plays?username=texasjdl&id=84876",
    "sample_data/plays?username=texasjdl&id=84876&type=thing",
    "sample_data/plays?username=texasjdl&page=1",
    "sample_data/plays?username=texasjdl&page=2",
    "sample_data/plays?username=texasjdl&page=3",
    "sample_data/plays?username=yyyyyyy&page=1",
    "sample_data/search?query=Burgun",
    "sample_data/search?query=Burgun&exact=1",
    "sample_data/search?query=Burgund&type=boardgame",
    "sample_data/search?query=The+Castles+of+Burgundy&exact=1",
    "sample_data/search?query=yyyyyyy",
    "sample_data/thing?id=10000000&type=boardgame",
    "sample_data/thing?id=29773&type=boardgame",
    "sample_data/thing?id=70512&type=boardgame",
    "sample_data/thing?id=84876&type=boardgame",
    "sample_data/user?name=texasjdl",
    "sample_data/user?name=yyyyyyy",
    "spec/bgg_api_spec.rb",
    "spec/bgg_collection_item_spec.rb",
    "spec/bgg_collection_spec.rb",
    "spec/bgg_game_spec.rb",
    "spec/bgg_play_spec.rb",
    "spec/bgg_plays_iterator_spec.rb",
    "spec/bgg_plays_spec.rb",
    "spec/bgg_search_result_spec.rb",
    "spec/bgg_search_spec.rb",
    "spec/bgg_user_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jemiahlee/bgg"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "object-oriented boardgamegeek api gem"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
      s.add_development_dependency(%q<codeclimate-test-reporter>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<xml-simple>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<codeclimate-test-reporter>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<xml-simple>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<codeclimate-test-reporter>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

